### ISSUE TITLE
Value for WS_URL for websockets 

### ISSUE THREAD

**Issue by AlexisNvn** [Polymarket/clob-client#127]
Hi there, 
What would be the value of WS_URL / host to access websockets ? 

Tried wss://clob.polymarket.com but doesn't seem to work.

**Comment by AlexisNvn** [comment]
Nevermind, found it : wss://ws-subscriptions-clob.polymarket.com/ws/

**Comment by AlexisNvn** [comment]
Update this url doesn't seem to work anymore, getting 404 errors with : 

```python
import websockets
import asyncio

poly_host = "wss://ws-subscriptions-clob.polymarket.com/ws/"

async def test():
    async with websockets.connect(poly_host) as websocket:
        print("connected")

asyncio.run(test())
```

Anything I'm doing it wrong or is url from doc not up to date ? 
https://docs.polymarket.com/#endpoints

**Comment by AlexisNvn** [comment]
My bad, seems the host need to be : 
wss://ws-subscriptions-clob.polymarket.com/ws/user to access User data
or 
wss://ws-subscriptions-clob.polymarket.com/ws/market to access Market data

**Comment by Andreas-Hadjiantoni** [comment]
@AlexisNvn Are you able to subscribe to the user channel? I get: "Error:  Connection to remote host was lost.  " but I'm not sure if I'm doing something wrong.
