### ISSUE TITLE
How to use it? Is it publicly available?

### ISSUE THREAD

**Issue by arekgotfryd** [Polymarket/clob-client#43]
Hello,

I would love to play around with this client but at the moment I have no idea how.
I configured my .env file as follows
```
RPC_URL=https://polygon-mumbai.infura.io/v3/infuraidentifirer
PK=0xMY_PRIVATE_KEY
CLOB_API_KEY=
CLOB_SECRET=
CLOB_PASS_PHRASE=
CLOB_API_URL=https://clob.polymarket.com/
```
I left CLOB_API_KEY, CLOB_SECRET and CLOB_PASS_PHRASE blank.
Then I tried to run createApiKey.ts and I'm getting 405 Method Not Allowed.
What am I missing?

**Comment by JonathanAmenechi** [comment]
Hi @arekgotfryd, the production CLOB API is geoblocked. You are welcome to use the staging API, which runs on Mumbai testnet at https://clob-staging.polymarket.com.

See the polymarket clob documentation for more details(contract addresses, endpoints, etc): https://polymarket.gitbook.io/clob/#rest-endpoint

**Comment by capaj** [comment]
@JonathanAmenechi both links return 404.
can you specify-why is this open source when I cannot use it as polymarket user?
